docker_backend:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin https://index.docker.io/v1/
  script:
    - docker build -t nielshen/teamprojekt:flask-backend -f betterclassroom-backend/Dockerfile .
    - docker push nielshen/teamprojekt:flask-backend

docker_frontend:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin https://index.docker.io/v1/
  script:
    - docker build -t nielshen/teamprojekt:vue-frontend -f betterclassroom-frontend/Dockerfile .
    - docker push nielshen/teamprojekt:vue-frontend
