stages:
  - docker

docker_backend:
  stage: docker
  image: docker:latest
  services:
    - name: docker:latest-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker buildx create --use
    - docker buildx inspect --bootstrap
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 -t nielshen/teamprojekt:flask-backend --file betterclassroom-backend/Dockerfile --push .
  tags:
    - docker

docker_frontend:
  stage: docker
  image: docker:latest
  services:
    - name: docker:latest-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker buildx create --use
    - docker buildx inspect --bootstrap
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 -t nielshen/teamprojekt:vue-frontend --file betterclassroom-frontend/Dockerfile --push .
  tags:
    - docker
