stages:
  - build
  - deploy

build_frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/betterclassroom-frontend"
      --dockerfile "${CI_PROJECT_DIR}/betterclassroom-frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_NAME}"

build_backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/betterclassroom-backend"
      --dockerfile "${CI_PROJECT_DIR}/betterclassroom-backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_REF_NAME}"