stages:
  - docker

docker_backend:
  stage: docker
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--privileged"]
      network_mode: "host"
  variables:
    DOCKER_HOST: "tcp://docker:2375"
  before_script:
    - unset DOCKER_HOST
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin https://index.docker.io/v1/
  script:
    - docker build -t nielshen/teamprojekt:flask-backend -f betterclassroom-backend/Dockerfile .
    - docker push nielshen/teamprojekt:flask-backend


docker_frontend:
  stage: docker
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--privileged"]
      network_mode: "host"
  variables:
    DOCKER_HOST: "tcp://docker:2375"
  before_script:
    - unset DOCKER_HOST
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin https://index.docker.io/v1/
  script:
    - docker build -t nielshen/teamprojekt:vue-frontend -f betterclassroom-frontend/Dockerfile .
    - docker push nielshen/teamprojekt:vue-frontend