stages:
  - docker

docker_backend:
  stage: docker
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
      command: ["--iptables=false"]
      privileged: true
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  script:
    - docker build -t nielshen/teamprojekt:flask-backend -f betterclassroom-backend/Dockerfile .
    - docker push nielshen/teamprojekt:flask-backend

docker_frontend:
  stage: docker
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
      command: ["--iptables=false"]
      privileged: true
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  script:
    - docker build -t nielshen/teamprojekt:vue-frontend -f betterclassroom-frontend/Dockerfile .
    - docker push nielshen/teamprojekt:vue-frontend
