stages:
  - build
  - push

build_frontend:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/vue-frontend ./betterclassroom-frontend

build_backend:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/flask-backend ./betterclassroom-backend

push_frontend:
  stage: push
  image: docker:stable
  services:
    - name: docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker push $CI_REGISTRY_IMAGE/vue-frontend

push_backend:
  stage: push
  image: docker:stable
  services:
    - name: docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker push $CI_REGISTRY_IMAGE/flask-backend
