stages:
  - build
  - push

build_frontend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t nielshen/teamprojekt:vue-frontend ./betterclassroom-frontend

build_backend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t nielshen/teamprojekt:flask-backend ./betterclassroom-backend

push_frontend:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAM" --password-stdin
    - docker tag frontend_image:latest nielshen/teamprojekt:vue-frontend
    - docker push nielshen/teamprojekt:vue-frontend

push_backend:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAM" --password-stdin
    - docker tag backend_image:latest nielshen/teamprojekt:flask-backend
    - docker push nielshen/teamprojekt:flask-backend
