apiVersion: apps/v1
kind: Deployment
metadata:
  name: mein-backend
  namespace: betterclassroom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mein-backend
  template:
    metadata:
      labels:
        app: mein-backend
    spec:
      containers:
        - name: mein-backend
          image: registry.gitlab.in.htwg-konstanz.de/lehre/meiglspe/sose24/betterclassroom/backend:0.0.7 #TODO: set to current feature branch name or on production and main to image tag name
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: my-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mein-backend
  namespace: betterclassroom
spec:
  selector:
    app: mein-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP