apiVersion: apps/v1
kind: Deployment
metadata:
  name: mein-frontend
  namespace: betterclassroom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mein-frontend
  template:
    metadata:
      labels:
        app: mein-frontend
    spec:
      containers:
        - name: mein-frontend
          image: registry.gitlab.in.htwg-konstanz.de/lehre/meiglspe/sose24/betterclassroom/frontend:47-als-dozent-mochte-ich-die-moglichkeit-haben-uber-markdown-aufgaben-und-unteraufgaben-zu #TODO: set to current feature branch name or on production and main to image tag name
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: my-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mein-frontend
  namespace: betterclassroom
spec:
  selector:
    app: mein-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP