apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: my-app-repo
  namespace: flux-system
spec:
  image: registry.gitlab.in.htwg-konstanz.de/lehre/meiglspe/sose24/betterclassroom/backend #TODO: frotend
  secretRef:
    name: my-registry-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: my-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: my-app-repo
  policy:
    numerical:
      order: asc #Accepted Image Version Tags sorted by alphabet order
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: update-my-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: my-app-repo
  interval: 1m # search for image updates
  git:
    commit:
      author:
        name: Flux
        email: flux@yourdomain.com
  update:
    strategy: Setters

#spec:
 # update:
  #  strategy: Setters
   # path: ./app
  #git:
   # checkout: # moved under `git`, loses `gitRepositoryRef`
    #  ref:
     #   branch: main # moved into `ref` struct
    #commit: # moved under `git`
     # author:
      #  name: fluxbot  # moved from `authorName`
       # email: fluxbot@example.com # moved from `authorEmail`
      #messageTemplate: |
       # An automated update from FluxBot
        #[ci skip]
      #signingKey:
       # secretRef:
        #  name: git-pgp
    #push: # moved under `git`
     # branch: auto