apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: my-app-repo
  namespace: flux-system
spec:
  image: registry.gitlab.in.htwg-konstanz.de/lehre/meiglspe/sose24/betterclassroom/backend #TODO: frotend
  #branch: main
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: my-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: my-app-repo
  policy:
    semver:
      range: "*" #Accepted Image Versions
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: update-my-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: my-app-repo
  interval: 1m # search for image updates
  git:
    commit:
      authorName: Flux
      authorEmail: flux@yourdomain.com
  update:
    strategy: Setters