---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mongodb
  namespace: betterclassroom
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: betterclassroom
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: mongodb
      version: 15.1.7
      sourceRef:
        kind: HelmRepository
        name: mongodb
      interval: 5m
  releaseName: mongodb
  values:
    auth:
      enabled: false
    username: admin
    password: admin
