---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mongodb
  namespace: betterclassroom
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: betterclassroom
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: mongodb
      version: 15.4.3
      sourceRef:
        kind: HelmRepository
        name: mongodb
      interval: 5m
  releaseName: mongodb
  values:
    image:
      tag: "4.4.29"  # Selected MongoDB version < v5 because the HTWG VM lacks the AVX instruction set.
    auth:
      enabled: false #enable auth in Production
 #   username: admin
  #  password: admin
