apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: spa-redirect
  namespace: betterclassroom
spec:
  errors:
    status:
      - "404"
    service:
      name: mein-frontend
      port: 80
    query: "/index.html"
